services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network_1610
  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:1.6.1.0
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html:cached
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      DB_SERVER: mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: password
    networks:
      - prestashop_network_1610
networks:
    prestashop_network_1610:
